[book]
authors = ["Lorenz Schmidt"]
language = "en"
multilingual = false
src = "src"
title = "Rust Machine Learning Book"

[preprocessor.scientific]
# Only run the `foo` preprocessor for the HTML renderer
renderer = ["html"]

bibliography = "literature.bib"
bib2xhtml = ""

assets = "src/"

[output.html]
additional-css = ["src/scientific.css"]
