[package]
name = "code"
version = "0.1.0"
authors = ["chrism"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plotters = "0.3"
ndarray = "0.13"
linfa = "0.3"
linfa-clustering = "0.3"
rand = { version = "0.7", features = ["small_rng"] }